variant = "loose"

[[issues]]
file = "src/ConfigProvider.php"
code = "class-must-be-final"
message = 'Class `Webware\Log\ConfigProvider` should be declared `final`.'
count = 1

[[issues]]
file = "src/ConfigProvider.php"
code = "invalid-return-statement"
message = '''Invalid return type for function `Webware\Log\ConfigProvider::__invoke`: expected `array{'dependencies': array{'aliases': array{Psr\EventDispatcher\EventDispatcherInterface::class: class-string, Psr\EventDispatcher\ListenerProviderInterface::class: class-string}, 'delegators': array{Laminas\Stratigility\Middleware\ErrorHandler::class: list<class-string>}, 'factories': array{Phly\EventDispatcher\ListenerProvider\ListenerProviderAggregate::class: class-string, Psr\Log\LoggerInterface::class: class-string, Webware\Log\Handler\PhpDbHandler::class: class-string, Webware\Log\Http\Middleware\MonologMiddleware::class: class-string, Webware\Log\Listener\Psr3LogPsr14Listener::class: class-string, Webware\Log\Processor\LaminasI18nProcessor::class: class-string}, 'invokables': array{Phly\EventDispatcher\ListenerProvider\AttachableListenerProvider::class: class-string, Phly\EventDispatcher\ListenerProvider\PrioritizedListenerProvider::class: class-string, Webware\Log\Processor\RamseyUuidProcessor::class: class-string}}, 'listener_providers': array<array-key, array{}|false|float(0.0)|int(0)|null|string('')|string('0')>, 'listeners': array<class-string, list<array{'listener': class-string, 'priority': int}>>, 'templates': array{'paths': array{'log': list<string>}}, Psr\Log\LoggerInterface::class: array{'auth_attribute': string, 'channel': string, 'log_errors': bool, 'process_translation': bool, 'process_uuid': bool, 'table': string}}`, but found `array{'Psr\Log\LoggerInterface': array{'auth_attribute': string, 'channel': string, 'log_errors': bool, 'process_translation': bool, 'process_uuid': bool, 'table': string}, 'dependencies': array{'aliases': array{Psr\EventDispatcher\EventDispatcherInterface::class: class-string, Psr\EventDispatcher\ListenerProviderInterface::class: class-string}, 'delegators': array{Laminas\Stratigility\Middleware\ErrorHandler::class: list<class-string>}, 'factories': array{Phly\EventDispatcher\ListenerProvider\ListenerProviderAggregate::class: class-string, Psr\Log\LoggerInterface::class: class-string, Webware\Log\Handler\PhpDbHandler::class: class-string, Webware\Log\Http\Middleware\MonologMiddleware::class: class-string, Webware\Log\Listener\Psr3LogPsr14Listener::class: class-string, Webware\Log\Processor\LaminasI18nProcessor::class: class-string}, 'invokables': array{Phly\EventDispatcher\ListenerProvider\AttachableListenerProvider::class: class-string, Phly\EventDispatcher\ListenerProvider\PrioritizedListenerProvider::class: class-string, Webware\Log\Processor\RamseyUuidProcessor::class: class-string}}, 'listener_providers': array{}, 'listeners': array<class-string, list<array{'listener': class-string, 'priority': int}>>, 'templates': array{'paths': array{'log': list<string>}}}`.'''
count = 1

[[issues]]
file = "src/ConfigProvider.php"
code = "invalid-return-statement"
message = '''Invalid return type for function `Webware\Log\ConfigProvider::getDependencies`: expected `array{'aliases': array{Psr\EventDispatcher\EventDispatcherInterface::class: class-string, Psr\EventDispatcher\ListenerProviderInterface::class: class-string}, 'delegators': array{Laminas\Stratigility\Middleware\ErrorHandler::class: list<class-string>}, 'factories': array{Phly\EventDispatcher\ListenerProvider\ListenerProviderAggregate::class: class-string, Psr\Log\LoggerInterface::class: class-string, Webware\Log\Handler\PhpDbHandler::class: class-string, Webware\Log\Http\Middleware\MonologMiddleware::class: class-string, Webware\Log\Listener\Psr3LogPsr14Listener::class: class-string, Webware\Log\Processor\LaminasI18nProcessor::class: class-string}, 'invokables': array{Phly\EventDispatcher\ListenerProvider\AttachableListenerProvider::class: class-string, Phly\EventDispatcher\ListenerProvider\PrioritizedListenerProvider::class: class-string, Webware\Log\Processor\RamseyUuidProcessor::class: class-string}}`, but found `array{'aliases': array{'Psr\EventDispatcher\EventDispatcherInterface': class-string('Phly\EventDispatcher\EventDispatcher'), 'Psr\EventDispatcher\ListenerProviderInterface': class-string('Phly\EventDispatcher\ListenerProvider\ListenerProviderAggregate')}, 'delegators': array{'Laminas\Stratigility\Middleware\ErrorHandler': list{class-string('Webware\Log\Container\MezzioErrorHandlerDelegator')}}, 'factories': array{'Phly\EventDispatcher\ListenerProvider\ListenerProviderAggregate': class-string('Webware\Log\Container\ListenerProviderAggregateFactory'), 'Psr\Log\LoggerInterface': class-string('Webware\Log\Container\LogFactory'), 'Webware\Log\Handler\PhpDbHandler': class-string('Webware\Log\Handler\PhpDbHandlerFactory'), 'Webware\Log\Http\Middleware\MonologMiddleware': class-string('Webware\Log\Http\Middleware\Container\MonologMiddlewareFactory'), 'Webware\Log\Listener\Psr3LogPsr14Listener': class-string('Webware\Log\Listener\Psr3LogPsr14ListenerFactory'), 'Webware\Log\Processor\LaminasI18nProcessor': class-string('Webware\Log\Processor\LaminasI18nProcessorFactory')}, 'invokables': array{'Phly\EventDispatcher\ListenerProvider\AttachableListenerProvider': class-string('Phly\EventDispatcher\ListenerProvider\AttachableListenerProvider'), 'Phly\EventDispatcher\ListenerProvider\PrioritizedListenerProvider': class-string('Phly\EventDispatcher\ListenerProvider\PrioritizedListenerProvider'), 'Webware\Log\Processor\RamseyUuidProcessor': class-string('Webware\Log\Processor\RamseyUuidProcessor')}}`.'''
count = 1

[[issues]]
file = "src/Container/ListenerProviderAggregateFactory.php"
code = "impossible-type-comparison"
message = "Impossible type assertion: `$listener` of type `class-string` can never be `(callable(...mixed): mixed)`."
count = 1

[[issues]]
file = "src/Container/ListenerProviderAggregateFactory.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "src/Container/ListenerProviderAggregateFactory.php"
code = "no-value"
message = 'Argument #2 passed to method `Phly\EventDispatcher\ListenerProvider\AttachableListenerProvider::listen` has type `never`, meaning it cannot produce a value.'
count = 1

[[issues]]
file = "src/Container/ListenerProviderAggregateFactory.php"
code = "possibly-undefined-string-array-index"
message = "Possibly undefined array key accessed on `array{'listener': (callable(...mixed): mixed)|class-string, 'priority'?: int}|array{0: class-string|object, 1: non-empty-string}`."
count = 2

[[issues]]
file = "src/Container/ListenerProviderAggregateFactory.php"
code = "redundant-logical-operation"
message = "Redundant `&&` operation: left operand is evaluated and right operand is always truthy."
count = 1

[[issues]]
file = "src/Container/ListenerProviderAggregateFactory.php"
code = "redundant-type-comparison"
message = "Redundant type assertion: `$listener['priority']` is already `int`."
count = 1

[[issues]]
file = "src/Container/LogFactory.php"
code = "impossible-condition"
message = "Redundant ternary operator: condition is always falsy."
count = 1

[[issues]]
file = "src/Container/LogFactory.php"
code = "impossible-nonnull-entry-check"
message = '''Impossible `isset` check on key `'Psr\Log\LoggerInterface'` accessed on `array{Psr\Log\LoggerInterface::class?: array{'auth_attribute': string, 'channel': string, 'log_errors': bool, 'process_translation': bool, 'process_uuid': bool, 'table': string}}`.'''
count = 1

[[issues]]
file = "src/Container/LogFactory.php"
code = "redundant-null-coalesce"
message = "Redundant null coalesce: left-hand side can never be `null` or undefined."
count = 2

[[issues]]
file = "src/Container/MezzioErrorHandlerDelegator.php"
code = "impossible-nonnull-entry-check"
message = '''Impossible `isset` check on key `'Psr\Log\LoggerInterface'` accessed on `array{Psr\Log\LoggerInterface::class?: array{'auth_attribute': string, 'channel': string, 'log_errors': bool, 'process_translation': bool, 'process_uuid': bool, 'table': string}}`.'''
count = 1

[[issues]]
file = "src/Container/MezzioErrorHandlerDelegator.php"
code = "redundant-null-coalesce"
message = "Redundant null coalesce: left-hand side is always `null`."
count = 1

[[issues]]
file = "src/Container/MezzioErrorHandlerDelegator.php"
code = "unused-parameter"
message = "Parameter `$name` is never used."
count = 1

[[issues]]
file = "src/Event/LogEvent.php"
code = "class-must-be-final"
message = 'Class `Webware\Log\Event\LogEvent` should be declared `final`.'
count = 1

[[issues]]
file = "src/Handler/PhpDbHandlerFactory.php"
code = "impossible-condition"
message = "Redundant ternary operator: condition is always falsy."
count = 1

[[issues]]
file = "src/Handler/PhpDbHandlerFactory.php"
code = "impossible-nonnull-entry-check"
message = '''Impossible `isset` check on key `'Psr\Log\LoggerInterface'` accessed on `array{'authentication'?: array{'username'?: string}, Psr\Log\LoggerInterface::class?: array{'auth_attribute': string, 'channel': string, 'log_errors': bool, 'process_translation': bool, 'process_uuid': bool, 'table': string}}`.'''
count = 1

[[issues]]
file = "src/Http/Middleware/Container/MonologMiddlewareFactory.php"
code = "class-must-be-final"
message = 'Class `Webware\Log\Http\Middleware\Container\MonologMiddlewareFactory` should be declared `final`.'
count = 1

[[issues]]
file = "src/Http/Middleware/Container/MonologMiddlewareFactory.php"
code = "impossible-nonnull-entry-check"
message = '''Impossible `isset` check on key `'Psr\Log\LoggerInterface'` accessed on `array{Psr\Log\LoggerInterface::class?: array{'auth_attribute': string, 'channel': string, 'log_errors': bool, 'process_translation': bool, 'process_uuid': bool, 'table': string}}`.'''
count = 1

[[issues]]
file = "src/Http/Middleware/Container/MonologMiddlewareFactory.php"
code = "redundant-null-coalesce"
message = "Redundant null coalesce: left-hand side is always `null`."
count = 1

[[issues]]
file = "src/Http/Middleware/MonologMiddleware.php"
code = "class-must-be-final"
message = 'Class `Webware\Log\Http\Middleware\MonologMiddleware` should be declared `final`.'
count = 1
